# Hesap makinesi olarak Python

Python basit hesaplamalar için mükemmel bir seçimdir. Toplama, çıkarma, çarpma ve bölme işlemlerini yapabilir.Komuttaki kodda birkaç örnek veriliyor. Şimdi sıra sizde, kendiniz kod yazarak alıştırma yapın.

Talimatlar
- print() fonksiyonunu kullanarak # Subtraction altında 5 değerinden 5 çıkarma işleminin sonucunu yazdırın.
- Multiplication altında 3 ile 5 çarpımının sonucunu yazdırın.


In [1]:
# Addition and division
print(4 + 5)
print(10 / 2)

# Subtraction
print(5 - 5)

# Multiplication
print(3 * 5)

9
5.0
0
15


# Değişkenler

- Spesifik, büyük/küçük harf duyarlı bir isim
- Değişken ismi ile değeri çağırabilme
- 1.79 m - 68.7 kg

In [2]:
height = 1.79
weight = 68.7
height

1.79

In [3]:
weight / height ** 2

21.44127836209856

In [4]:
bmi = weight / height ** 2
bmi


21.44127836209856

In [5]:
height = 1.79
weight = 74.2
bmi = weight / height ** 2
print(bmi)

23.157829031553323


type() fonksiyonu, Python'da bir değişkenin, değerin veya ifadenin hangi veri tipine (örneğin int, float, str, bool vb.) sahip olduğunu görmek için kullanılır. 


In [6]:
type(bmi) 

float

In [7]:
x = "body mass index"
y = 'this works too'
type(x)

str

In [8]:
z = True
type(z)

bool

In [9]:
2+3

5

In [10]:
'ab' + 'cd'

'abcd'

Değişken Atama

Python’da değişken, bir değere ad ile başvurmanıza olanak tanır. 5 değerine sahip bir x değişkeni oluşturmak için aşağıdaki örnekte olduğu gibi = işlecini kullanırsınız:

x = 5
Artık bu değişkenin gerçek değeri olan 5 yerine adı olan x değerini kullanabilirsiniz.

Unutmayın, Python’da =, atama anlamına gelir, eşitliği test etmez! ____ ifadesini kendi kodunuzla değiştirerek egzersizde deneyin.

Talimatlar
- 100 değerine sahip bir savings değişkeni oluşturun.
- Komuta print(savings) yazarak bu değişkeni kontrol edin.


In [11]:
savings = 100
print(savings)

100


Değişkenlerle hesaplamalar

Bir savings değişkeni oluşturduğunuza göre para biriktirmeye başlayalım!

Gerçek değerlerle hesaplama yapmak yerine değişkenleri kullanabilirsiniz.

Her ay $10 biriktirseydiniz dört ay sonunda ne kadar para biriktirmiş olurdunuz?

Talimatlar
- 10 değerine eşit bir monthly_savings değişkeni ve 4 değerine eşit bir num_months değişkeni oluşturun.
- monthly_savings değerini num_months ile çarpın ve new_savings sütununa atayın.
- new_savings değerini yazdırın

In [12]:
# Create the variables monthly_savings and num_months
monthly_savings = 10
num_months = 4


# Multiply monthly_savings and num_months
new_savings = num_months * monthly_savings

# Print new_savings
print(new_savings)

40


---
Diğer Değişken Türleri
---

Önceki egzersizde tamsayı (integer, int) veri türüyle çalıştınız.

- int (tamsayı): Kesirli kısmı olmayan sayılar. Örneğin: `100`
- float (kayan noktalı sayı): Ondalık kısım içeren sayılar, örneğin: `1.1`
- str (dize): Metni temsil eder. Tek veya çift tırnak kullanılabilir, örneğin: `"Merhaba"`
- bool (mantıksal): Sadece `True` veya `False` değerlerini alır. Mantıksal işlemler için kullanılır.

Aşağıdaki değişkenleri oluşturun:

- half isminde, değeri `0.5` olan bir float
- intro isminde, değeri `"Hello! How are you?"` olan bir str
- is_good isminde, değeri `True` olan bir bool

---

In [13]:
# Create a variable half
half = 0.5

# Create a variable intro
intro = "Hello! How are you?"

# Create a variable is_good
is_good = True


Diğer türlerle işlemler

Python’da değişkenler farklı türlerde olabilir. type() fonksiyonunu kullanarak bir değişkenin türünü görebilirsiniz. Örneğin a türünü görmek için type(a) komutunu yürütün.

Python’da farklı türler farklı şekilde davranır. Örneğin iki dizeyi topladığınızda, iki tamsayı veya iki boole değerini topladığınızda elde edeceğinizden farklı bir sonuç elde edersiniz.

Şimdi bunu deneme zamanı.

Talimatlar 1/2
1. savings ile new_savings değerlerini toplayıp total_savings değişkenine atayın. Elde edilen total_savings türünü yazdırmak için type() komutunu kullanın.
2. intro ile intro değerlerinin toplamını hesaplayın ve sonucu doubleintro değişkenine atayın.
doubleintro değerini yazdırın. Bu sonucu bekliyor muydunuz?

In [14]:
savings = 100
new_savings = 40

# Calculate total_savings using savings and new_savings
total_savings = savings + new_savings
print(total_savings)

# Print the type of total_savings
print(type(total_savings))

140
<class 'int'>


In [15]:
intro = "Hello! How are you?"

# Assign sum of intro and intro to doubleintro
doubleintro = intro + intro

# Print out doubleintro
print(doubleintro)

Hello! How are you?Hello! How are you?


### Liste oluşturma

Liste bir bileşik veri türüdür. Listedeki değerleri şunun gibi gruplandırabilirsiniz:
```
a = "is"
b = "nice"
my_list = ["my", "list", a, b]
```

Ailenizdeki herkesin boyunu ölçtükten sonra yaşadığınız ev hakkında bazı bilgiler toplamaya karar veriyorsunuz. Evinizin farklı bölümlerinin alanları, egzersizde ayrı değişkenlerde depolanır.

Talimatlar

- areas adlı bir liste oluşturun ve bu listeye sırasıyla koridorun (hall), mutfağın (kit), oturma odasının (liv), yatak odasının (bed) ve banyonun (bath) alanını yazın. Önceden tanımlanmış değişkenleri kullanın.
- print() fonksiyonunu kullanarak areas sonucunu yazdırın.


In [16]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## Farklı türlerde listeler oluşturma

Çok yaygın olmasa da bir liste; dizeler, kayan sayılar ve boole değerleri dahil olmak üzere çeşitli Python türlerini içerebilir.

Şimdi oda adlarını listenize ekleyeceksiniz, böylece oda adını ve büyüklüğünü birlikte kolayca görebileceksiniz.

Başlamanız için size bazı kodlar verilmiştir. Buraya dikkat edin! "bathroom" bir dizedir, bath ise daha önce belirttiğiniz 9.50 kayan değerini temsil eden bir değişkendir.

Talimatlar

- areas listesini oluşturan kodu tamamlayın. Listeyi, önce bir dize olarak her odanın adını ve ardından alanını içerecek şekilde oluşturun. Diğer bir deyişle "hallway", "kitchen" ve "bedroom" dizelerini uygun yerlere ekleyin.
- areas sonucunu tekrar yazdırın; bu sefer çıktı daha bilgilendirici oldu mu?


In [17]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


## Listelerin listesi

Bir veri bilimcisi olarak, çoğu zaman çok fazla veriyle uğraşacaksınız ve bu verilerin bir kısmını gruplandırmak mantıklı olacak.

Evinizdeki odaların adlarını ve alanlarını temsil eden dizeler ve kayan sayılar içeren bir liste oluşturmak yerine listelerin bir listesini oluşturabilirsiniz.

Unutmayın: "hallway" bir dizedir, hall ise daha önce belirttiğiniz 11.25 kayan değerini temsil eden bir değişkendir.

Talimatlar
- Liste listesini, yatak odası ve banyo verilerini de içerecek şekilde tamamlayın. Doğru sırayla girdiğinizden emin olun!
- house sonucunu yazdırın; verilerinizi bu şekilde yapılandırmak daha mantıklı mı oldu?

In [18]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ["bathroom", bath]
        ]

# Print out house
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


## Alt kümelere böl ve yönet

Python listelerinin alt kümelerini oluşturmak çocuk oyuncağıdır. x listesini oluşturan ve ardından bu listeden "b" seçimi yapan aşağıdaki kod örneğini alın. Bunun ikinci eleman olduğunu, dolayısıyla dizininin 1 olduğunu unutmayın. Negatif dizinlemeyi de kullanabilirsiniz.

```
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!
```

Daha önce gördüğümüz, hem dizeleri hem de kayan sayıları içeren areas listesini hatırlıyor musunuz? Tanımı zaten kodda var. Python alt kümesi oluşturmak için doğru kodu ekleyebilir misiniz?

Talimatlar
- areas listesinden ikinci elemanı yazdırın (11.25 değerine sahiptir).
- areas listesinin alt kümesini oluşturun değeri 9.50 olan son elemanı yazdırın. Burada negatif dizin kullanmak mantıklıdır!
- Oturma odasının alanını temsil eden sayıyı (20.0) seçin ve yazdırın.



In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[-5])

11.25
9.5
20.0


## Dilimlemek ve doğramak

Bir listeden tek bir değer seçmek, işin sadece bir kısmıdır. Listenizi dilimlemek, yani listenizden birden fazla eleman seçmek de mümkündür. Aşağıdaki sözdizimini kullanın:

my_list[start:end]

start dizini dahil edilir ancak end dizini dahil edilmez. Ancak bu dizinleri belirtmeme seçeneği de mevcuttur. start dizinini belirtmezseniz Python, dilimleme işleminin listenin başından başlamasını istediğinizi anlar.

Talimatlar
- Dilimlemeyi kullanarak, areas listesindeki ilk 6 elemanı içeren bir downstairs listesi oluşturun.
- areas listesinin son 4 elemanı olarak upstairs listesini oluşturun. Bu kez end dizinini atlayarak dilimlemeyi basitleştirin.
- print() fonksiyonunu kullanarak downstairs ve upstairs sonuçlarını yazdırın.


In [20]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


### Listelerin listesinin alt kümelerini oluşturma

Bir Python listesi başka listeler de içerebilir.

Listelerin alt kümelerini oluşturmak için daha önce kullandığımız tekniği kullanabilirsiniz: köşeli parantezler. Bu bir house listesi için şunun gibi görünecektir:

house[2][0]

Talimatlar

- house listesinin alt kümesini oluşturarak 9.5 kayan sayısını elde edin.


In [21]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[4][1]

9.5

## Liste elemanlarını değiştirme

Liste elemanlarını değiştirmek için, listenin alt kümesini oluşturun ve alt kümeye yeni değerler atayın. Elemanları tek tek seçebilir veya tüm liste dilimlerini tek seferde değiştirebilirsiniz.

Bu ve sonraki egzersizlerde bir evdeki farklı odaların adlarını ve alanlarını içeren areas listesi üzerinde çalışmaya devam edeceksiniz.

Talimatlar
- Negatif dizinleme kullanarak banyonun alanını 9.50 metrekare yerine 10.50 metrekare olarak güncelleyin.
- areas listesini daha modaya uygun hale getirin! "living room" adını "chill zone" olarak değiştirin. Bu sefer negatif dizinleme kullanmayın.

In [22]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

## Listeyi genişletme
Bir listedeki elemanları değiştirebiliyorsanız listeye eleman ekleyebilmeniz de mümkün olmalıdır, değil mi? + işlecini kullanabilirsiniz:
```
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
```

Muhteşem bir şey oldu ve piyango size çıktı! Havuzlu bir ev ve garaj inşa etmeye karar verdiniz. Bu bilgileri areas listesine ekleyebilir misiniz?

Talimatlar
- artı + işlecini kullanarak ["poolhouse", 24.5] listesini areas listesinin sonuna yapıştırın. Elde edilen listeyi areas_1 olarak kaydedin.
- Garajınızla ilgili bilgileri ekleyerek areas_1 listesini daha da genişletin. "garage" dizesini ve 15.45 kayan sayısını ekleyin. Ortaya çıkan listeye areas_2 adını verin.


In [23]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage",15.45]

## Liste elemanlarını silme


Son olarak, listenizden eleman da silebilirsiniz. Bunu del ifadesiyle yapabilirsiniz:
```
x = ["a", "b", "c", "d"]
del x[1]
```

Burada dikkatli olun: Bir elemanı listeden kaldırdığınız anda silinen elemanın ardından gelen tüm elemanların dizinleri değişir!

Maalesef piyangoda kazandığınız miktar o kadar da büyük değil ve havuzlu ev hayali suya düşecek gibi görünüyor. Bunu listeden kaldırmanız gerekecek. areas listesinden ilgili dizeyi ve kayan sayıyı kaldırmaya karar veriyorsunuz.

Talimatlar
- areas listenizden "poolhouse" dizesini ve kayan sayısını silin.
- Güncellenen areas listesini yazdırın.

In [24]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Delete the poolhouse items from the list
del areas[-4:-2]

# Print the updated list
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


### Listelerin iç işleyişi

Bu egzersizde size bazı kodlar verilmiştir: areas adlı bir liste ve areas_copy adlı bir kopya.

Şu anda, areas_copy listesinin ilk elemanı değiştirildi ve areas listesi yazdırıldı. Çalıştır düğmesine basarsanız, areas_copy kopyasını değiştirmiş olmanıza rağmen değişikliğin areas listesine de uygulandığını göreceksiniz. Bunun nedeni, areas listesi ile areas_copy kopyasının aynı listeyi işaret etmesidir.

areas_copy kopyasındaki değişikliklerin areas listesine de uygulanmasını istemiyorsanız list() ile veya [:] kullanarak areas listesinin daha açık bir kopyasını oluşturmanız gerekir.

areas_copy değişkenini oluşturan ikinci komutu, areas_copy kopyası areas listesinin açık bir kopyası olacak şekilde değiştirin. Düzenlemenizden sonra areas_copy kopyasında yapılan değişiklikler areas listesini etkilemeyecektir. Bunu kontrol etmek için yanıtı gönde

In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change this command
areas_copy = list(areas) # veya areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[5.0, 18.0, 20.0, 10.75, 9.5]


In [26]:
x = [1,2,3]
y = x
y[0] = -1
print(x)

[-1, 2, 3]


## Tanıdık fonksiyonlar

Python, veri bilimcisi olarak hayatınızı kolaylaştırmak için bir dizi yerleşik fonksiyon sunar. Bu türden iki fonksiyonu zaten biliyorsunuz: print() ve type(). Veri türleri arasında geçiş yapmak için str(), int(), bool() ve float() gibi fonksiyonlar da bulunur. Bunları burada bulabilirsiniz. Bunlar da yerleşik fonksiyonlardır.

Bir fonksiyonu çağırmak kolaydır. 3.0 türünü almak ve çıktıyı yeni bir result değişkeni olarak kaydetmek için aşağıdakileri kullanabilirsiniz:

result = type(3.0)

Talimatlar

- print() fonksiyonunu type() ile birlikte kullanarak var1 türünü yazdırabilirsiniz.
- len() fonksiyonunu kullanarak var1listesinin uzunluğunu alın. Bir print() çağrısında sarmalayarak doğrudan yazdırın.
- var2 listesini bir tamsayıya dönüştürmek için int() fonksiyonunu kullanın. Çıktıyı out2 olarak kaydedin.

In [1]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


## Birden fazla bağımsız değişken

Önceki egzersizde help() ile belgeleri görüntüleyerek isteğe bağlı bağımsız değişkenleri belirlediniz. Şimdi bunu sorted() fonksiyonunun davranışını değiştirmek için uygulayacaksınız.

IPython Shell’de help(sorted) yazarak sorted() belgelerine göz atın.

Göreceğiniz gibi sorted() üç bağımsız değişken alır: iterable, key ve reverse. Bu egzersizde yalnızca iterable ve reverse bağımsız değişkenlerini belirtmeniz gerekir, key bağımsız değişkenini belirtmenize gerek yoktur.

Sizin için iki liste oluşturulmuştur.

Bunları birleştirip azalan düzende sıralayabilir misiniz?

# Talimatlar
- + işlecini kullanarak first ve second içeriklerini yeni bir listede birleştirin: full.
- sorted() fonksiyonunu çağırın ve full listesinde reverse bağımsız değişkenini True olarak belirtin. - - Sıralanmış listeyi full_sorted olarak kaydedin.
- Son olarak full_sorted sonucunu yazdırın.

In [2]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


## Dize Yöntemleri
Dizeler bir dizi yöntemle birlikte gelir. Bu yöntemlerden bazılarını keşfetmek için talimatları dikkatlice izleyin. Bunları daha ayrıntılı olarak keşfetmek isterseniz IPython Shell’e help(str) yazabilirsiniz.

Denemeler yapmanız için bir place dizesi oluşturulmuştur.

#### Talimatlar
- place dizesinde .upper() yöntemini kullanın ve sonucu place_up içinde depolayın. Önceki videoda öğrendiğiniz yöntemleri çağırmaya yönelik sözdizimini kullanın.
- place ve place_up sonuçlarının çıktısını alın. İkisi de değişti mi?
- place değişkeni üzerinde .count() çağrısı yaparak ve 'o' harfini yönteme girdi olarak geçirerek place değişkenindeki o’ların sayısını yazdırın. place değişkeninden bahsediyoruz, "place" sözcüğünden değil!


In [3]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


## Liste Yöntemleri
Kendileriyle ilişkili yöntemleri olan tek Python türleri dizeler değildir. Listeler, kayan sayılar, tamsayılar ve boole değerleri de bir dizi kullanışlı yöntem içeren türlerdir. Bu egzersizde şunları deneyeceksiniz:

Bir listenin ilk elemanıyla eşleşen dizini almak için .index() ve
Bir elemanın bir listede görünme sayısını almak için .count().
Bir evin farklı bölümlerinin alanlarını içeren bir liste üzerinde çalışacaksınız: areas.


### Talimatlar
- .index() yöntemini kullanarak areas listesinde 20.0 ile eşit olan elemanın dizinini alın. Bu dizini yazdırın.
- 9.50 değerinin listede kaç kez geçtiğini öğrenmek için areas listesinde .count() çağrısı yapın. Bu sayıyı da yazdırın.




In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))


## Liste Yöntemleri (2)
Çoğu liste yöntemi, üzerinde çağrıldıkları listeyi değiştirir. Örnekler:

Çağrıldığı listeye bir eleman ekleyen .append().
Bir listenin girdiyle eşleşen birinci elemanını kaldıran .remove() ve
Üzerinde çağrıldığı listedeki elemanların sırasını tersine çeviren .reverse().
Evin farklı bölümlerinin alanlarını içeren liste üzerinde çalışacaksınız: areas.


## Talimatlar
- .append() çağrısını iki kez kullanarak havuzlu evin ve garajın boyutunu tekrar ekleyin: sırasıyla 24.5 ve 15.45. Bunları bu sırayla eklediğinizden emin olun.
- areas listesini yazdırın.
- .reverse() yöntemini kullanarak areas listesindeki elemanların sırasını tersine çevirin.
areas listesini bir kez daha yazdırın.

In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)


## Paketi içe aktarma
Bir dairenin çevresini ve alanını hesaplamak istediğinizi varsayalım. Bu formüller şu şekilde görünür:


pi sayısını yazmak yerine sayıyı içeren math paketini kullanabilirsiniz.

Referans olarak **, üs alma işleminin sembolüdür. Örneğin 3**4, 3 üzeri 4 anlamına gelip 81 sonucunu verir.

## Talimatlar
- math paketini içe aktarın.
- math.pi fonksiyonunu kullanarak dairenin çevresini hesaplayın ve C içinde depolayın.
- math.pi fonksiyonunu kullanarak dairenin alanını hesaplayın ve A içinde depolayın.


In [4]:
# Import the math package
import math

# Calculate C
C = 2 * 0.43 * math.pi

# Calculate A
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


## Seçici içe aktarma
import math gibi genel içe aktarmalar, math paketindeki tüm fonksiyonları kullanıma açar. Ancak bir paketin yalnızca belirli bir bölümünü kullanmaya karar verirseniz, içe aktarımı her zaman daha seçici hale getirebilirsiniz:

from math import pi

Aynı şeyi tekrar deneyin ancak bu sefer sadece pi kullanın.

Talimatlar

- math paketinden yalnızca pi fonksiyonunu içe aktararak seçici bir içe aktarma gerçekleştirin.
- pi fonksiyonunu kullanarak dairenin çevresini hesaplayın ve C içinde depolayın.
- pi fonksiyonunu kullanarak dairenin alanını hesaplayın ve A içinde depolayın.

In [5]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527
